# Generated by Django 5.1.6 on 2025-02-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Название специальности"
            ),
        ),
    ]
