# Generated by Django 5.1.6 on 2025-02-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0002_alter_specialty_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="actual_address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Фактический адрес"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="inn",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="ИНН"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="kpp",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="КПП"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="legal_address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Юридический адрес"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="ogrn",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="ОГРН"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
