# Generated by Django 5.1.6 on 2025-02-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0003_alter_organization_actual_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intern",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
