# Generated by Django 5.1.6 on 2025-02-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0004_alter_intern_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название тега"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="intern",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/", verbose_name="Резюме"
            ),
        ),
        migrations.AddField(
            model_name="intern",
            name="resume_access_granted",
            field=models.BooleanField(default=False, verbose_name="Доступ к резюме"),
        ),
        migrations.AddField(
            model_name="intern",
            name="tags",
            field=models.ManyToManyField(blank=True, to="doc.tag", verbose_name="Теги"),
        ),
    ]
