# Generated by Django 5.1.6 on 2025-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0005_tag_intern_resume_intern_resume_access_granted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intern",
            name="resume_access_granted",
        ),
        migrations.AddField(
            model_name="organization",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Подтверждено"),
        ),
    ]
