# Generated by Django 5.1.6 on 2025-02-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0006_remove_intern_resume_access_granted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Пароль"
            ),
        ),
    ]
