# Generated by Django 5.1.6 on 2025-02-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0007_organization_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_registration_request",
            field=models.BooleanField(
                default=False, verbose_name="Заявка на регистрацию"
            ),
        ),
    ]
