# Generated by Django 5.1.6 on 2025-02-25 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0008_organization_is_registration_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="doc.specialty",
                verbose_name="Специальность",
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="college_supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doc.collegesupervisor",
                verbose_name="Руководитель от техникума",
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doc.group",
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doc.organization",
                verbose_name="Организация",
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="doc.group",
                verbose_name="Группа",
            ),
        ),
    ]
