# Generated by Django 5.1.6 on 2025-03-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0009_alter_group_specialty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intern",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
    ]
