# Generated by Django 5.1.6 on 2025-03-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0010_intern_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email_sent",
            field=models.BooleanField(default=False, verbose_name="Письмо отправлено"),
        ),
    ]
