# Generated by Django 5.1.6 on 2025-03-03 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0011_account_email_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название документа"),
                ),
                ("file", models.FileField(upload_to="documents/", verbose_name="Файл")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, to="doc.group", verbose_name="Группы"
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        blank=True, to="doc.specialty", verbose_name="Специальности"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doc.account",
                        verbose_name="Загружено",
                    ),
                ),
            ],
        ),
    ]
