# Generated by Django 5.1.6 on 2025-03-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0012_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="managed_groups",
            field=models.ManyToManyField(
                blank=True, to="doc.group", verbose_name="Управляемые группы"
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="pm",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Профессиональный модуль",
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="pp",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Производственная практика",
            ),
        ),
    ]
