# Generated by Django 5.1.6 on 2025-03-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0013_account_managed_groups_alter_practice_pm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practice",
            name="group",
        ),
        migrations.AddField(
            model_name="practice",
            name="group",
            field=models.ManyToManyField(to="doc.group", verbose_name="Группы"),
        ),
    ]
