# Generated by Django 5.1.6 on 2025-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0014_remove_practice_group_practice_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practice",
            name="group",
        ),
        migrations.AddField(
            model_name="practice",
            name="groups",
            field=models.ManyToManyField(to="doc.group", verbose_name="Группы"),
        ),
    ]
