# Generated by Django 5.1.6 on 2025-03-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0015_remove_practice_group_practice_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="documents",
            field=models.ManyToManyField(
                blank=True, to="doc.document", verbose_name="Документы"
            ),
        ),
    ]
