# Generated by Django 5.1.6 on 2025-03-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0016_practice_documents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="document",
            name="specialties",
        ),
        migrations.RemoveField(
            model_name="practice",
            name="documents",
        ),
        migrations.AddField(
            model_name="document",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doc.practice",
                verbose_name="Практика",
            ),
        ),
    ]
