# Generated by Django 5.1.6 on 2025-03-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0017_remove_document_groups_remove_document_specialties_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="managed_groups",
            field=models.ManyToManyField(
                blank=True, null=True, to="doc.group", verbose_name="Управляемые группы"
            ),
        ),
    ]
