# Generated by Django 5.1.6 on 2025-03-26 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0019_interviewinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewinvitation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AddField(
            model_name="interviewinvitation",
            name="status_changed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата изменения статуса"
            ),
        ),
    ]
