# Generated by Django 5.1.6 on 2025-03-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0022_alter_interviewinvitation_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_auto_fillable",
            field=models.BooleanField(default=False, verbose_name="Автозаполняемый"),
        ),
    ]
