# Generated by Django 5.1.6 on 2025-04-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0023_document_is_auto_fillable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Классификация"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="specialty",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Специальность"),
        ),
    ]
