# Generated by Django 5.1.6 on 2025-04-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0025_specialty_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doc.classification",
                verbose_name="Классификация",
            ),
        ),
    ]
