name: Build Windows EXE
on:
  push:
    branches: [ main ]  # Запуск при пуше в main
  workflow_dispatch:    # Ручной запуск через Actions tab

jobs:
  build:
    runs-on: windows-latest  # Windows-сервер GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller django psycopg2-binary
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile --name=myapp main.py
          # Если нужно добавить скрытые импорты Django:
          # pyinstaller --onefile --hidden-import=django.core.management --hidden-import=myapp.apps myapp.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp.exe
          path: dist/myapp.exe